-- =====================================================
-- SYNAPSE HEALTHCARE ANALYTICS PLATFORM
-- STEP 3: Snowflake Data Warehouse Setup
-- Run in Snowflake Worksheet (ACCOUNTADMIN or SYSADMIN)
-- =====================================================

-- ─────────────────────────────────────────────────────
-- 1. INFRASTRUCTURE SETUP
-- ─────────────────────────────────────────────────────

-- Warehouse (compute cluster — X-Small is enough for dev)
CREATE WAREHOUSE IF NOT EXISTS SYNAPSE_WH
    WAREHOUSE_SIZE    = 'X-SMALL'
    AUTO_SUSPEND      = 60          -- suspend after 60s idle (cost control)
    AUTO_RESUME       = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Synapse Healthcare Analytics Compute';

-- Database
CREATE DATABASE IF NOT EXISTS SYNAPSE_DB
    COMMENT = 'Synapse Healthcare Analytics Platform';

USE DATABASE SYNAPSE_DB;
USE WAREHOUSE SYNAPSE_WH;

-- Schemas
CREATE SCHEMA IF NOT EXISTS RAW        COMMENT = 'As-landed data from SQL Server';
CREATE SCHEMA IF NOT EXISTS STAGING    COMMENT = 'Cleaned and validated data';
CREATE SCHEMA IF NOT EXISTS ANALYTICS  COMMENT = 'Star schema — Power BI source';
CREATE SCHEMA IF NOT EXISTS SUMMARY    COMMENT = 'Python/LLM generated KPI summaries';
GO

-- Roles & access (optional: for team setup)
-- CREATE ROLE SYNAPSE_ANALYST;
-- GRANT USAGE ON WAREHOUSE SYNAPSE_WH TO ROLE SYNAPSE_ANALYST;
-- GRANT SELECT ON ALL TABLES IN SCHEMA SYNAPSE_DB.ANALYTICS TO ROLE SYNAPSE_ANALYST;


-- ─────────────────────────────────────────────────────
-- 2. STAGING TABLES (mirror of SQL Server stg schema)
--    Python ETL writes here first
-- ─────────────────────────────────────────────────────

USE SCHEMA STAGING;

CREATE OR REPLACE TABLE STAGING.HOSPITAL (
    HOSPITAL_ID     NUMBER,
    HOSPITAL_NAME   VARCHAR(100),
    CITY            VARCHAR(50),
    STATE           VARCHAR(50),
    TIER            VARCHAR(10),
    TOTAL_BEDS      NUMBER,
    ICU_BEDS        NUMBER,
    VENTILATORS     NUMBER,
    LAT             FLOAT,
    LON             FLOAT,
    DQ_FLAG         NUMBER DEFAULT 0,
    STG_LOAD_TS     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE STAGING.DEPARTMENT (
    DEPARTMENT_ID   NUMBER,
    HOSPITAL_ID     NUMBER,
    DEPARTMENT_NAME VARCHAR(50),
    TOTAL_BEDS      NUMBER,
    FLOOR_NUMBER    NUMBER,
    STG_LOAD_TS     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE STAGING.AMBULANCE (
    AMBULANCE_ID        NUMBER,
    REGISTRATION_NO     VARCHAR(20),
    HOSPITAL_ID         NUMBER,
    VEHICLE_TYPE        VARCHAR(20),
    MANUFACTURE_YEAR    NUMBER,
    STATUS              VARCHAR(20),
    STG_LOAD_TS         TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE STAGING.DIM_DATE (
    DATE_ID         NUMBER,
    FULL_DATE       DATE,
    DAY_OF_WEEK     VARCHAR(10),
    DAY_NUM         NUMBER,
    WEEK_NUM        NUMBER,
    MONTH_NUM       NUMBER,
    MONTH_NAME      VARCHAR(15),
    QUARTER         NUMBER,
    YEAR            NUMBER,
    IS_WEEKEND      BOOLEAN,
    IS_HOLIDAY      BOOLEAN,
    STG_LOAD_TS     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE STAGING.BED_OCCUPANCY (
    OCCUPANCY_ID    NUMBER,
    DEPARTMENT_ID   NUMBER,
    HOSPITAL_ID     NUMBER,
    DATE_ID         NUMBER,
    SNAPSHOT_HOUR   NUMBER,
    SNAPSHOT_TS     TIMESTAMP_NTZ,
    TOTAL_BEDS      NUMBER,
    OCCUPIED_BEDS   NUMBER,
    AVAILABLE_BEDS  NUMBER,
    OCCUPANCY_PCT   FLOAT,
    ON_HOLD_BEDS    NUMBER,
    CRITICAL_FLAG   NUMBER,
    STG_LOAD_TS     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE STAGING.AMBULANCE_DISPATCH (
    DISPATCH_ID             NUMBER,
    AMBULANCE_ID            NUMBER,
    HOSPITAL_ID             NUMBER,
    DATE_ID                 NUMBER,
    CALL_TIMESTAMP          TIMESTAMP_NTZ,
    DISPATCH_TIMESTAMP      TIMESTAMP_NTZ,
    ON_SCENE_TIMESTAMP      TIMESTAMP_NTZ,
    HOSPITAL_ARRIVAL_TS     TIMESTAMP_NTZ,
    CALL_TYPE               VARCHAR(20),
    CALL_OUTCOME            VARCHAR(30),
    RESPONSE_TIME_MIN       NUMBER,
    ON_SCENE_TIME_MIN       NUMBER,
    TRANSPORT_TIME_MIN      NUMBER,
    TOTAL_TIME_MIN          NUMBER,
    SLA_BREACHED            NUMBER,
    CREW_COUNT              NUMBER,
    STG_LOAD_TS             TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE STAGING.PATIENT_FLOW (
    FLOW_ID                 NUMBER,
    PATIENT_ID              VARCHAR(15),
    HOSPITAL_ID             NUMBER,
    DEPARTMENT_ID           NUMBER,
    ADMIT_DATE_ID           NUMBER,
    ADMIT_TIMESTAMP         TIMESTAMP_NTZ,
    DISCHARGE_TIMESTAMP     TIMESTAMP_NTZ,
    LENGTH_OF_STAY_HRS      NUMBER,
    CONDITION               VARCHAR(50),
    ENTRY_MODE              VARCHAR(20),
    AGE_GROUP               VARCHAR(10),
    GENDER                  CHAR(1),
    ER_TO_WARD_HRS          FLOAT,
    READMISSION_FLAG        NUMBER,
    DISCHARGE_TYPE          VARCHAR(20),
    STG_LOAD_TS             TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


-- ─────────────────────────────────────────────────────
-- 3. ANALYTICS STAR SCHEMA
-- ─────────────────────────────────────────────────────

USE SCHEMA ANALYTICS;

-- DIMENSION: Hospital
CREATE OR REPLACE TABLE ANALYTICS.DIM_HOSPITAL (
    HOSPITAL_SK     NUMBER AUTOINCREMENT PRIMARY KEY,  -- surrogate key
    HOSPITAL_ID     NUMBER NOT NULL,                    -- natural key
    HOSPITAL_NAME   VARCHAR(100),
    CITY            VARCHAR(50),
    STATE           VARCHAR(50),
    TIER            VARCHAR(10),
    TOTAL_BEDS      NUMBER,
    ICU_BEDS        NUMBER,
    VENTILATORS     NUMBER,
    LAT             FLOAT,
    LON             FLOAT,
    EFF_FROM        DATE DEFAULT CURRENT_DATE(),
    EFF_TO          DATE DEFAULT '9999-12-31',
    IS_CURRENT      BOOLEAN DEFAULT TRUE
);

-- DIMENSION: Department
CREATE OR REPLACE TABLE ANALYTICS.DIM_DEPARTMENT (
    DEPARTMENT_SK   NUMBER AUTOINCREMENT PRIMARY KEY,
    DEPARTMENT_ID   NUMBER NOT NULL,
    HOSPITAL_ID     NUMBER,
    DEPARTMENT_NAME VARCHAR(50),
    TOTAL_BEDS      NUMBER,
    FLOOR_NUMBER    NUMBER
);

-- DIMENSION: Ambulance
CREATE OR REPLACE TABLE ANALYTICS.DIM_AMBULANCE (
    AMBULANCE_SK        NUMBER AUTOINCREMENT PRIMARY KEY,
    AMBULANCE_ID        NUMBER NOT NULL,
    REGISTRATION_NO     VARCHAR(20),
    HOSPITAL_ID         NUMBER,
    VEHICLE_TYPE        VARCHAR(20),
    MANUFACTURE_YEAR    NUMBER,
    STATUS              VARCHAR(20)
);

-- DIMENSION: Date (pre-built calendar)
CREATE OR REPLACE TABLE ANALYTICS.DIM_DATE (
    DATE_ID         NUMBER PRIMARY KEY,
    FULL_DATE       DATE,
    DAY_OF_WEEK     VARCHAR(10),
    DAY_NUM         NUMBER,
    WEEK_NUM        NUMBER,
    MONTH_NUM       NUMBER,
    MONTH_NAME      VARCHAR(15),
    QUARTER         NUMBER,
    YEAR            NUMBER,
    IS_WEEKEND      BOOLEAN,
    IS_HOLIDAY      BOOLEAN
);

-- FACT: Bed Occupancy
CREATE OR REPLACE TABLE ANALYTICS.FACT_BED_OCCUPANCY (
    OCCUPANCY_SK        NUMBER AUTOINCREMENT PRIMARY KEY,
    DEPARTMENT_SK       NUMBER REFERENCES ANALYTICS.DIM_DEPARTMENT(DEPARTMENT_SK),
    HOSPITAL_SK         NUMBER REFERENCES ANALYTICS.DIM_HOSPITAL(HOSPITAL_SK),
    DATE_ID             NUMBER REFERENCES ANALYTICS.DIM_DATE(DATE_ID),
    SNAPSHOT_HOUR       NUMBER,
    SNAPSHOT_TS         TIMESTAMP_NTZ,
    TOTAL_BEDS          NUMBER,
    OCCUPIED_BEDS       NUMBER,
    AVAILABLE_BEDS      NUMBER,
    OCCUPANCY_PCT       FLOAT,
    ON_HOLD_BEDS        NUMBER,
    CRITICAL_FLAG       NUMBER
)
CLUSTER BY (DATE_ID, HOSPITAL_SK);     -- clustering = faster Power BI queries

-- FACT: Ambulance Dispatch
CREATE OR REPLACE TABLE ANALYTICS.FACT_AMBULANCE_DISPATCH (
    DISPATCH_SK             NUMBER AUTOINCREMENT PRIMARY KEY,
    AMBULANCE_SK            NUMBER REFERENCES ANALYTICS.DIM_AMBULANCE(AMBULANCE_SK),
    HOSPITAL_SK             NUMBER REFERENCES ANALYTICS.DIM_HOSPITAL(HOSPITAL_SK),
    DATE_ID                 NUMBER REFERENCES ANALYTICS.DIM_DATE(DATE_ID),
    CALL_TIMESTAMP          TIMESTAMP_NTZ,
    DISPATCH_TIMESTAMP      TIMESTAMP_NTZ,
    ON_SCENE_TIMESTAMP      TIMESTAMP_NTZ,
    HOSPITAL_ARRIVAL_TS     TIMESTAMP_NTZ,
    CALL_TYPE               VARCHAR(20),
    CALL_OUTCOME            VARCHAR(30),
    RESPONSE_TIME_MIN       NUMBER,
    ON_SCENE_TIME_MIN       NUMBER,
    TRANSPORT_TIME_MIN      NUMBER,
    TOTAL_TIME_MIN          NUMBER,
    SLA_BREACHED            NUMBER,
    CREW_COUNT              NUMBER
)
CLUSTER BY (DATE_ID, HOSPITAL_SK);

-- FACT: Patient Flow
CREATE OR REPLACE TABLE ANALYTICS.FACT_PATIENT_FLOW (
    FLOW_SK                 NUMBER AUTOINCREMENT PRIMARY KEY,
    PATIENT_ID              VARCHAR(15),
    HOSPITAL_SK             NUMBER REFERENCES ANALYTICS.DIM_HOSPITAL(HOSPITAL_SK),
    DEPARTMENT_SK           NUMBER REFERENCES ANALYTICS.DIM_DEPARTMENT(DEPARTMENT_SK),
    DATE_ID                 NUMBER REFERENCES ANALYTICS.DIM_DATE(DATE_ID),
    ADMIT_TIMESTAMP         TIMESTAMP_NTZ,
    DISCHARGE_TIMESTAMP     TIMESTAMP_NTZ,
    LENGTH_OF_STAY_HRS      NUMBER,
    CONDITION               VARCHAR(50),
    ENTRY_MODE              VARCHAR(20),
    AGE_GROUP               VARCHAR(10),
    GENDER                  CHAR(1),
    ER_TO_WARD_HRS          FLOAT,
    READMISSION_FLAG        NUMBER,
    DISCHARGE_TYPE          VARCHAR(20)
)
CLUSTER BY (DATE_ID, HOSPITAL_SK);


-- ─────────────────────────────────────────────────────
-- 4. SUMMARY SCHEMA (Python/LLM writes here)
-- ─────────────────────────────────────────────────────

USE SCHEMA SUMMARY;

CREATE OR REPLACE TABLE SUMMARY.DAILY_KPI_SUMMARY (
    SUMMARY_ID          NUMBER AUTOINCREMENT PRIMARY KEY,
    REPORT_DATE         DATE,
    HOSPITAL_ID         NUMBER,
    HOSPITAL_NAME       VARCHAR(100),
    AVG_OCCUPANCY_PCT   FLOAT,
    PEAK_OCCUPANCY_PCT  FLOAT,
    CRITICAL_DEPT_COUNT NUMBER,
    TOTAL_DISPATCHES    NUMBER,
    AVG_RESPONSE_MIN    FLOAT,
    SLA_BREACH_COUNT    NUMBER,
    SLA_BREACH_PCT      FLOAT,
    TOTAL_ADMISSIONS    NUMBER,
    TOTAL_DISCHARGES    NUMBER,
    AVG_LOS_HRS         FLOAT,
    READMISSION_COUNT   NUMBER,
    CREATED_TS          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE SUMMARY.LLM_NARRATIVES (
    NARRATIVE_ID        NUMBER AUTOINCREMENT PRIMARY KEY,
    REPORT_DATE         DATE,
    HOSPITAL_ID         NUMBER,
    NARRATIVE_TYPE      VARCHAR(30),    -- 'daily_ops', 'weekly_exec', 'alert'
    NARRATIVE_TEXT      VARCHAR(4000),
    MODEL_USED          VARCHAR(50),
    PROMPT_TOKENS       NUMBER,
    COMPLETION_TOKENS   NUMBER,
    CREATED_TS          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


-- ─────────────────────────────────────────────────────
-- 5. ELT TRANSFORMS (staging → analytics)
-- Run AFTER Python loads staging tables
-- ─────────────────────────────────────────────────────

-- Populate DIM_HOSPITAL
INSERT INTO ANALYTICS.DIM_HOSPITAL (
    HOSPITAL_ID, HOSPITAL_NAME, CITY, STATE, TIER,
    TOTAL_BEDS, ICU_BEDS, VENTILATORS, LAT, LON
)
SELECT HOSPITAL_ID, HOSPITAL_NAME, CITY, STATE, TIER,
       TOTAL_BEDS, ICU_BEDS, VENTILATORS, LAT, LON
FROM STAGING.HOSPITAL
WHERE DQ_FLAG = 0;

-- Populate DIM_DEPARTMENT
INSERT INTO ANALYTICS.DIM_DEPARTMENT (
    DEPARTMENT_ID, HOSPITAL_ID, DEPARTMENT_NAME, TOTAL_BEDS, FLOOR_NUMBER
)
SELECT DEPARTMENT_ID, HOSPITAL_ID, DEPARTMENT_NAME, TOTAL_BEDS, FLOOR_NUMBER
FROM STAGING.DEPARTMENT;

-- Populate DIM_AMBULANCE
INSERT INTO ANALYTICS.DIM_AMBULANCE (
    AMBULANCE_ID, REGISTRATION_NO, HOSPITAL_ID, VEHICLE_TYPE, MANUFACTURE_YEAR, STATUS
)
SELECT AMBULANCE_ID, REGISTRATION_NO, HOSPITAL_ID, VEHICLE_TYPE, MANUFACTURE_YEAR, STATUS
FROM STAGING.AMBULANCE;

-- Populate DIM_DATE
INSERT INTO ANALYTICS.DIM_DATE
SELECT DATE_ID, FULL_DATE, DAY_OF_WEEK, DAY_NUM, WEEK_NUM,
       MONTH_NUM, MONTH_NAME, QUARTER, YEAR, IS_WEEKEND, IS_HOLIDAY
FROM STAGING.DIM_DATE;

-- Populate FACT_BED_OCCUPANCY (join to resolve SK)
INSERT INTO ANALYTICS.FACT_BED_OCCUPANCY (
    DEPARTMENT_SK, HOSPITAL_SK, DATE_ID,
    SNAPSHOT_HOUR, SNAPSHOT_TS,
    TOTAL_BEDS, OCCUPIED_BEDS, AVAILABLE_BEDS,
    OCCUPANCY_PCT, ON_HOLD_BEDS, CRITICAL_FLAG
)
SELECT
    dd.DEPARTMENT_SK,
    dh.HOSPITAL_SK,
    bo.DATE_ID,
    bo.SNAPSHOT_HOUR,
    bo.SNAPSHOT_TS,
    bo.TOTAL_BEDS, bo.OCCUPIED_BEDS, bo.AVAILABLE_BEDS,
    bo.OCCUPANCY_PCT, bo.ON_HOLD_BEDS, bo.CRITICAL_FLAG
FROM STAGING.BED_OCCUPANCY bo
JOIN ANALYTICS.DIM_DEPARTMENT dd ON bo.DEPARTMENT_ID = dd.DEPARTMENT_ID
JOIN ANALYTICS.DIM_HOSPITAL   dh ON bo.HOSPITAL_ID   = dh.HOSPITAL_ID AND dh.IS_CURRENT = TRUE;

-- Populate FACT_AMBULANCE_DISPATCH
INSERT INTO ANALYTICS.FACT_AMBULANCE_DISPATCH (
    AMBULANCE_SK, HOSPITAL_SK, DATE_ID,
    CALL_TIMESTAMP, DISPATCH_TIMESTAMP, ON_SCENE_TIMESTAMP, HOSPITAL_ARRIVAL_TS,
    CALL_TYPE, CALL_OUTCOME,
    RESPONSE_TIME_MIN, ON_SCENE_TIME_MIN, TRANSPORT_TIME_MIN, TOTAL_TIME_MIN,
    SLA_BREACHED, CREW_COUNT
)
SELECT
    da.AMBULANCE_SK,
    dh.HOSPITAL_SK,
    ad.DATE_ID,
    ad.CALL_TIMESTAMP, ad.DISPATCH_TIMESTAMP, ad.ON_SCENE_TIMESTAMP, ad.HOSPITAL_ARRIVAL_TS,
    ad.CALL_TYPE, ad.CALL_OUTCOME,
    ad.RESPONSE_TIME_MIN, ad.ON_SCENE_TIME_MIN, ad.TRANSPORT_TIME_MIN, ad.TOTAL_TIME_MIN,
    ad.SLA_BREACHED, ad.CREW_COUNT
FROM STAGING.AMBULANCE_DISPATCH ad
JOIN ANALYTICS.DIM_AMBULANCE  da ON ad.AMBULANCE_ID = da.AMBULANCE_ID
JOIN ANALYTICS.DIM_HOSPITAL   dh ON ad.HOSPITAL_ID  = dh.HOSPITAL_ID AND dh.IS_CURRENT = TRUE;

-- Populate FACT_PATIENT_FLOW
INSERT INTO ANALYTICS.FACT_PATIENT_FLOW (
    PATIENT_ID, HOSPITAL_SK, DEPARTMENT_SK, DATE_ID,
    ADMIT_TIMESTAMP, DISCHARGE_TIMESTAMP, LENGTH_OF_STAY_HRS,
    CONDITION, ENTRY_MODE, AGE_GROUP, GENDER,
    ER_TO_WARD_HRS, READMISSION_FLAG, DISCHARGE_TYPE
)
SELECT
    pf.PATIENT_ID,
    dh.HOSPITAL_SK,
    dd.DEPARTMENT_SK,
    pf.ADMIT_DATE_ID,
    pf.ADMIT_TIMESTAMP, pf.DISCHARGE_TIMESTAMP, pf.LENGTH_OF_STAY_HRS,
    pf.CONDITION, pf.ENTRY_MODE, pf.AGE_GROUP, pf.GENDER,
    pf.ER_TO_WARD_HRS, pf.READMISSION_FLAG, pf.DISCHARGE_TYPE
FROM STAGING.PATIENT_FLOW pf
JOIN ANALYTICS.DIM_HOSPITAL   dh ON pf.HOSPITAL_ID   = dh.HOSPITAL_ID AND dh.IS_CURRENT = TRUE
JOIN ANALYTICS.DIM_DEPARTMENT dd ON pf.DEPARTMENT_ID = dd.DEPARTMENT_ID;


-- ─────────────────────────────────────────────────────
-- 6. ANALYTICAL VIEWS (Power BI can use these directly)
-- ─────────────────────────────────────────────────────

-- View: Hospital capacity dashboard
CREATE OR REPLACE VIEW ANALYTICS.VW_HOSPITAL_CAPACITY AS
SELECT
    dh.HOSPITAL_NAME,
    dh.TIER,
    dd.DEPARTMENT_NAME,
    dt.FULL_DATE,
    dt.MONTH_NAME,
    dt.QUARTER,
    dt.YEAR,
    fo.SNAPSHOT_HOUR,
    fo.TOTAL_BEDS,
    fo.OCCUPIED_BEDS,
    fo.AVAILABLE_BEDS,
    fo.OCCUPANCY_PCT,
    fo.ON_HOLD_BEDS,
    fo.CRITICAL_FLAG,
    -- 7-day rolling average occupancy per department
    AVG(fo.OCCUPANCY_PCT) OVER (
        PARTITION BY fo.DEPARTMENT_SK
        ORDER BY dt.FULL_DATE
        ROWS BETWEEN 6 PRECEDING AND CURRENT ROW
    ) AS rolling_7d_avg_occ
FROM ANALYTICS.FACT_BED_OCCUPANCY fo
JOIN ANALYTICS.DIM_HOSPITAL   dh ON fo.HOSPITAL_SK   = dh.HOSPITAL_SK
JOIN ANALYTICS.DIM_DEPARTMENT dd ON fo.DEPARTMENT_SK = dd.DEPARTMENT_SK
JOIN ANALYTICS.DIM_DATE       dt ON fo.DATE_ID       = dt.DATE_ID;

-- View: Ambulance operations
CREATE OR REPLACE VIEW ANALYTICS.VW_AMBULANCE_OPS AS
SELECT
    dh.HOSPITAL_NAME,
    da.VEHICLE_TYPE,
    da.REGISTRATION_NO,
    dt.FULL_DATE,
    dt.MONTH_NAME,
    dt.DAY_OF_WEEK,
    dt.IS_WEEKEND,
    fad.CALL_TYPE,
    fad.CALL_OUTCOME,
    fad.RESPONSE_TIME_MIN,
    fad.ON_SCENE_TIME_MIN,
    fad.TRANSPORT_TIME_MIN,
    fad.TOTAL_TIME_MIN,
    fad.SLA_BREACHED,
    fad.CREW_COUNT,
    -- Percentile ranking of response times
    PERCENT_RANK() OVER (
        PARTITION BY dh.HOSPITAL_SK, fad.CALL_TYPE
        ORDER BY fad.RESPONSE_TIME_MIN
    ) AS response_time_pctile
FROM ANALYTICS.FACT_AMBULANCE_DISPATCH fad
JOIN ANALYTICS.DIM_HOSPITAL   dh ON fad.HOSPITAL_SK  = dh.HOSPITAL_SK
JOIN ANALYTICS.DIM_AMBULANCE  da ON fad.AMBULANCE_SK = da.AMBULANCE_SK
JOIN ANALYTICS.DIM_DATE       dt ON fad.DATE_ID      = dt.DATE_ID;

-- View: Patient flow KPIs
CREATE OR REPLACE VIEW ANALYTICS.VW_PATIENT_FLOW AS
SELECT
    dh.HOSPITAL_NAME,
    dd.DEPARTMENT_NAME,
    dt.FULL_DATE,
    dt.MONTH_NAME,
    dt.QUARTER,
    pf.CONDITION,
    pf.ENTRY_MODE,
    pf.AGE_GROUP,
    pf.GENDER,
    pf.LENGTH_OF_STAY_HRS,
    pf.ER_TO_WARD_HRS,
    pf.READMISSION_FLAG,
    pf.DISCHARGE_TYPE,
    -- Average LOS by condition (window function)
    AVG(pf.LENGTH_OF_STAY_HRS) OVER (
        PARTITION BY pf.CONDITION
    ) AS avg_los_by_condition,
    -- Running admission count per hospital per month
    COUNT(*) OVER (
        PARTITION BY dh.HOSPITAL_SK, dt.MONTH_NUM, dt.YEAR
        ORDER BY pf.ADMIT_TIMESTAMP
    ) AS running_monthly_admissions
FROM ANALYTICS.FACT_PATIENT_FLOW pf
JOIN ANALYTICS.DIM_HOSPITAL   dh ON pf.HOSPITAL_SK   = dh.HOSPITAL_SK
JOIN ANALYTICS.DIM_DEPARTMENT dd ON pf.DEPARTMENT_SK = dd.DEPARTMENT_SK
JOIN ANALYTICS.DIM_DATE       dt ON pf.DATE_ID       = dt.DATE_ID;
